version: '3'
services:
  solr:
    container_name: solr-oscar
    image: solr:latest
    ports:
      - "8983:8983"
    volumes:
      - ./data/solr_data:/opt/solr/server/solr/mycores
  db:
    container_name: db-oscar
    image: postgres
    env_file: source/.env
    environment:
      POSTGRES_DB: main
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
       - ./data/db:/data/postgres
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin-oscar
    image: dpage/pgadmin4
    env_file: source/.env
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
